version: '3.9'

services:

  database:
    container_name: veryrezsi_database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # it is needed becasue the server starts up quicker than then database
      interval: 2s
      timeout: 20s
      retries: 10

  smtp:
    container_name: veryrezsi_smtp
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  server:
    container_name: veryrezsi_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      smtp:
        condition: service_started
      database:
        condition: service_healthy # this will make the server wait for the database to be healthy and ready

  client:
    container_name: veryrezsi_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
