@startuml expenses_usecase
title User actions use-case
"Add or remove expense" as (add_exp)
"List predefined expenses" as (list_pred)
"Save expenses" as (save_exp)
add_exp ..> list_pred : include
add_exp ..> save_exp : include
"List expenses" as (list_exp_all)
"Show connected user transactions" as (show_tr)
list_exp_all ..> show_tr : include
"Add transaction to expenses" as (add_tr)
actor "User" as user
user --> add_exp
user --> list_exp_all
user --> add_tr
@enduml
