@startuml user_interaction_usecase
title User interactions use-case
actor "User" as user
actor "Other user" as other_user
"Add other user" as (add_user)
"Request transaction from user" as (request_tr)
"Accept or Decline" as (aod)

user --> add_user
user --> request_tr
add_user -- aod
request_tr -- aod
other_user ---> aod
@enduml