[workspace]
members = [
    "migration",
    "entity"
]

[package]
authors = ["Attila Szőke <szokeattila9801@gmail.com>"]
name = "veryrezsi"
version = "0.2.0"
edition = "2021"
license = "MIT"

homepage = "https://github.com/szattila98/veryrezsi"
repository = "https://github.com/szattila98/veryrezsi"
documentation = "https://github.com/szattila98/veryrezsi"

description = """
Expense and subscription calculator web-server.
"""
readme = "README.md"
keywords = ["api", "calculator", "web-app", "expenses-manager", "rocket"]
categories = ["web-programming"]

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
axum = "0.5.15"
axum-extra = { version = "0.3.7", features = ["cookie-private"] }
tower = "0.4.13"
dotenvy = "0.15.1"
serde = "1.0.143"
serde_json = "1.0.83"
sea-orm = { version = "0.9.1", features = [ "sqlx-mysql", "runtime-tokio-rustls", "macros" ] }
entity = { path = "entity" }
migration = { path = "migration" }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
thiserror = "1.0.32"
pwhash = "1.0.0"
validator = { version = "0.16.0", features = ["derive"] }
chrono = "0.4.21"
lettre = { version = "0.10.1", default-features = false, features = ["builder", "smtp-transport", "pool", "tokio1-rustls-tls"] }
fancy-regex = "0.10.0"
lazy_static = "1.4.0"
handlebars = "4.3.3"
