[workspace]
members = [
    "api",
    "core",
    "migration",
    "entity"
]

[package]
authors = ["Attila Szőke <szokeattila9801@gmail.com>"]
name = "veryrezsi"
version = "0.2.0"
edition = "2021"
license = "MIT"

homepage = "https://github.com/szattila98/veryrezsi"
repository = "https://github.com/szattila98/veryrezsi"
documentation = "https://github.com/szattila98/veryrezsi"

description = """
Expense and subscription calculator web-server.
"""
readme = "README.md"
keywords = ["api", "calculator", "web-app", "expenses-manager", "rocket"]
categories = ["web-programming"]

[dependencies]
veryrezsi-api = { path = "api" }
