[debug]
port = 8000
workers = 4
keep_alive = 5
log_level = "normal"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="

[release]
port = 8000
workers = 4
keep_alive = 5
log_level = "critical"
# secret_key = specify in production
