[package]
name = "entity"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = "0.10.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
