[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = "0.9.1"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
